import { NgModule } from '@angular/core';

import {
    InputTextModule,
    InputTextareaModule,
    CalendarModule,
    AutoCompleteModule,
    ButtonModule,
    SplitButtonModule,
    DropdownModule,
    PasswordModule,
    ListboxModule,
    RadioButtonModule,
    DialogModule,
    PanelModule,
    DataGridModule,
    CarouselModule,
    OrderListModule,
    PickListModule,
    MenuModule,
    PanelMenuModule,
    TabViewModule,
    TreeModule,
    CodeHighlighterModule,
    MenubarModule,
    CardModule,
    ChartModule
} from 'primeng/primeng';

@NgModule({
    imports: [
        InputTextModule,
        InputTextareaModule,
        CalendarModule,
        AutoCompleteModule,
        ButtonModule,
        SplitButtonModule,
        DropdownModule,
        PasswordModule,
        ListboxModule,
        RadioButtonModule,
        DialogModule,
        PanelModule,
        DataGridModule,
        CarouselModule,
        OrderListModule,
        PickListModule,
        MenuModule,
        PanelMenuModule,
        TabViewModule,
        TreeModule,
        CodeHighlighterModule,
        MenubarModule,
        CardModule,
        ChartModule
    ],
    exports: [
        InputTextModule,
        InputTextareaModule,
        CalendarModule,
        AutoCompleteModule,
        ButtonModule,
        SplitButtonModule,
        DropdownModule,
        PasswordModule,
        ListboxModule,
        RadioButtonModule,
        DialogModule,
        PanelModule,
        DataGridModule,
        CarouselModule,
        OrderListModule,
        PickListModule,
        MenuModule,
        PanelMenuModule,
        TabViewModule,
        TreeModule,
        CodeHighlighterModule,
        MenubarModule,
        CardModule,
        ChartModule
    ]
})
export class PrimeNgModule { }